spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/withjpa?useUnicode=true&characterEncoding=utf8&useSSL=false

  jpa:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect